import 'package:user/models/MedipediaDTO.dart';
//https://www.e.com/watch?v=XsGXUriPKto
class MedipediaData{
  static List<MedipediaDTO> list=[
    new MedipediaDTO("Abdominal Aortic Aneurysm", "https://www.youtube.com/watch?v=3D5PPE8j0P8", "https://www.youtube.com/watch?v=Knz0uVnGTsQ", "https://www.youtube.com/watch?v=Of6NEJ3FtQM"),
    new MedipediaDTO("Acne", "https://www.youtube.com/watch?v=xXgGThbKe1E", "https://www.youtube.com/watch?v=7PAuX03Xda8", "https://www.youtube.com/watch?v=fcQwWbqjMW0"),
    new MedipediaDTO("Acute Cholecystitis", "https://www.youtube.com/watch?v=dGdQ-xWXOTE", "https://www.youtube.com/watch?v=R9YTJ7WID9U&t=32s", "https://www.youtube.com/watch?v=rEq5JqEb6Ts"),
    new MedipediaDTO("Acute Lymphoblastic Leukaemia", "https://www.youtube.com/watch?v=gacFUdmOX4Q", "https://www.youtube.com/watch?v=siM8ha_Lf8Q&list=PLi84xR239QffULDdbgyVonilocm2xHeLq", "https://www.youtube.com/watch?v=2ChCLC8VqTU"),
    new MedipediaDTO("Acute Lymphoblastic Leukaemia Children", "https://www.youtube.com/watch?v=_Mls5TViEhg", "https://www.youtube.com/watch?v=Z4szXwfRMsU", "https://www.youtube.com/watch?v=a8jU5G5PXQ0&t=51s"),
    new MedipediaDTO("Acute Lymphoblastic Leukaemia Teenagers and young Adults", "https://www.youtube.com/watch?v=nOTxdoDKRAI", "https://www.youtube.com/watch?v=BtKk4aeAnoE", "https://www.youtube.com/watch?v=s6B6MvX210M"),
    new MedipediaDTO("Acute Myeloid Leukaemia", "https://www.youtube.com/watch?v=IOit8rq6NBY", "https://www.youtube.com/watch?v=DKtJX-ZU1bs", "https://www.youtube.com/watch?v=CUDJPWqFhgQ&t=235s"),
    new MedipediaDTO("Acute Myeloid Leukaemia Children", "https://www.youtube.com/watch?v=xQa2d_rWwJY", "https://www.youtube.com/watch?v=44dsu9FETUY", "https://www.youtube.com/watch?v=C6_cFUGI-3k"),
    new MedipediaDTO("Acute Myeloid Leukaemia Teenagers and young Adults", "https://www.youtube.com/watch?v=IOit8rq6NBY&t=33s", "https://www.youtube.com/watch?v=DKtJX-ZU1bs", "https://www.youtube.com/watch?v=CUDJPWqFhgQ&t=30s"),
    new MedipediaDTO("Acute pancreatitis", "https://www.youtube.com/watch?v=inRSjh3bHPg", "https://www.youtube.com/watch?v=3Mhen8_z7dU", "https://www.youtube.com/watch?v=G1xxQLqBkaY"),
    new MedipediaDTO("Addison’s Disease", "https://www.youtube.com/watch?v=6JOrGaeQNIE", "https://www.youtube.com/watch?v=Zcyr8fV7deg", "https://www.youtube.com/watch?v=1AEPFheyqYE"),
    new MedipediaDTO("ADHD(Attention Deficit Hyperactivity Disorder)", "https://www.youtube.com/watch?v=hhK2L4NLCKU", "https://www.youtube.com/watch?v=BnGQSd4N2xc", "https://www.youtube.com/watch?v=02b_ftIesoA"),
    new MedipediaDTO("Alcohol Misuse", "https://www.youtube.com/watch?v=AWH7Fr8hNno", "https://www.youtube.com/watch?v=ujQzUy3_JcM", "https://www.youtube.com/watch?v=TRzf74Enpvk"),
    new MedipediaDTO("Alcohol Poisoning", "https://www.youtube.com/watch?v=6E_T_NQjJDo&t=41s", "https://www.youtube.com/watch?v=cfkpyUM_CqA", "https://www.youtube.com/watch?v=-qL9cWVIgb8"),
    new MedipediaDTO("Alcohol-Related liver Disease", "https://www.youtube.com/watch?v=AyJSgcZ6m5s", "https://www.youtube.com/watch?v=RudR2_Vvoaw", "https://www.youtube.com/watch?v=_6a3L00xoTU"),
    new MedipediaDTO("Allergic Rhinitis", "https://www.youtube.com/watch?v=IokODX8n0Pw", "https://www.youtube.com/watch?v=yp3vKEw_DaY&t=196s", "https://www.youtube.com/watch?v=3YkkNAvd9J4"),
    new MedipediaDTO("Allergies", "https://www.youtube.com/watch?v=f7aD4UpsitQ", "https://www.youtube.com/watch?v=yDiedlWRPIE", "https://www.youtube.com/watch?v=tASI4UrS2T0"),
    new MedipediaDTO("Alzheimer's Disease", "https://www.youtube.com/watch?v=yJXTXN4xrI8", "https://www.youtube.com/watch?v=CrYj0uv3VCY", "https://www.youtube.com/watch?v=OJp0BM5ujj0"),
    new MedipediaDTO("Anal Cancer", "https://www.youtube.com/watch?v=XeUKYgTqUNc", "https://www.youtube.com/watch?v=lO-LA9ejO_c", "https://www.youtube.com/watch?v=IFk5Ncx5HLA"),
    new MedipediaDTO("Anaphylaxis", "https://www.youtube.com/watch?v=G0__z1ADTbc&t=35s", "https://www.youtube.com/watch?v=yCKSUzZHmq8", "https://www.youtube.com/watch?v=yCKSUzZHmq8"),
    new MedipediaDTO("Angioedema", "https://www.youtube.com/watch?v=AnqVMDbPF4A", "https://www.youtube.com/watch?v=ZUJN_leHU2g", "https://www.youtube.com/watch?v=UCPoG4vPkkI"),
    new MedipediaDTO("Ankylosing Spondylitis", "https://www.youtube.com/watch?v=3cfcv3kffPc", "https://www.youtube.com/watch?v=pJ98aC6DxXM", "https://www.youtube.com/watch?v=TPqiLo3t7q4"),
    new MedipediaDTO("Anorexia Nervosa", "https://www.youtube.com/watch?v=eu0aic-NnWU", "https://www.youtube.com/watch?v=OMbpExKKKVo", "https://www.youtube.com/watch?v=B5kKcn7L400"),
    new MedipediaDTO("Anxiety Disorders in Children", "https://www.youtube.com/watch?v=ZSWIXwAB6Wg", "https://www.youtube.com/watch?v=r_5eiYIo1XM", "https://www.youtube.com/watch?v=hcn6boWLqJg"),
    new MedipediaDTO("Appendicitis", "https://www.youtube.com/watch?v=Pz33wxj6p0o", "https://www.youtube.com/watch?v=r2zsbdPBhGY", "https://www.youtube.com/watch?v=r9amif1DQMc"),
    new MedipediaDTO("Arthritis", "https://www.youtube.com/watch?v=gskB_Wgg-tI", "https://www.youtube.com/watch?v=7p8EH1Hcnoc", "https://www.youtube.com/watch?v=G6myAQ_Aljk"),
    new MedipediaDTO("Asbestosis", "https://www.youtube.com/watch?v=cWQeQW1z9qA", "https://www.youtube.com/watch?v=oOeGor4vYSM", "https://www.youtube.com/watch?v=ME4J_q585zM"),
    new MedipediaDTO("Asthma", "https://www.youtube.com/watch?v=S04dci7NTPk", "https://www.youtube.com/watch?v=PzfLDi-sL3w", "https://www.youtube.com/watch?v=7EDo9pUYvPE"),
    new MedipediaDTO("Atopic Eczema", "https://www.youtube.com/watch?v=97LjZ2XAtfY", "https://www.youtube.com/watch?v=gOH0VsKLQ3I", "https://www.youtube.com/watch?v=Fo9jygWAgsk"),
    new MedipediaDTO("Autism Spectrum Disorder(ASD)", "https://www.youtube.com/watch?v=0Pp8jcQ97pY", "https://www.youtube.com/watch?v=A-aLOiPzH84", "https://www.youtube.com/watch?v=BkxlJAvSfY4"),
    new MedipediaDTO("Bacterial Vaginosis", "https://www.youtube.com/watch?v=x9I2QUWOmM4", "https://www.youtube.com/watch?v=-Gt_NUed_sE", "https://www.youtube.com/watch?v=v2NFqN32epo"),
    new MedipediaDTO("Benign Prostate Enlargement", "https://www.youtube.com/watch?v=dQEGdv4Affc", "https://www.youtube.com/watch?v=Bcnz22XFFE0", "https://www.youtube.com/watch?v=k_aCg1n1hmE&t=46s"),
    new MedipediaDTO("Binge Eating", "https://www.youtube.com/watch?v=2pD0pjNCtX4", "https://www.youtube.com/watch?v=o10Iggq7afw", "https://www.youtube.com/watch?v=Heu2Nr2-dW0"),
    new MedipediaDTO("Bipolar Disorder", "https://www.youtube.com/watch?v=HWB0wQWJTew", "https://www.youtube.com/watch?v=Du59g22oS1A", "https://www.youtube.com/watch?v=L4nMmS2Nlzk"),
    new MedipediaDTO("Bladder Cancer", "https://www.youtube.com/watch?v=JrnAcyHoano", "https://www.youtube.com/watch?v=TT8GSMBRcps", "https://www.youtube.com/watch?v=jhIa4c-wh3s"),
    new MedipediaDTO("Blood Cancer", "https://www.youtube.com/watch?v=B8nFk5j2hP4", "https://www.youtube.com/watch?v=cbuzZMqL-AM", "https://www.youtube.com/watch?v=gacFUdmOX4Q&t=20s"),
    new MedipediaDTO("Bone Cancer", "https://www.youtube.com/watch?v=AWnpCNPCDOE", "https://www.youtube.com/watch?v=_Z3nLkvI6Hw&t=280s", "https://www.youtube.com/watch?v=2VSJ7nUZlRU"),
    new MedipediaDTO("Bowel Cancer", "https://www.youtube.com/watch?v=3--uKdyTbwk", "https://www.youtube.com/watch?v=xVxwF7_2qK4", "https://www.youtube.com/watch?v=_nAORckdIjY"),
    new MedipediaDTO("Bowel Incontinence", "https://www.youtube.com/watch?v=SCK-VC0IxJU", "https://www.youtube.com/watch?v=xDp4NK_umsE", "https://www.youtube.com/watch?v=wQawAoE3b6U"),
    new MedipediaDTO("Bowel Polyps", "https://www.youtube.com/watch?v=eD4TerMDdFs&t=72s", "https://www.youtube.com/watch?v=bI4HpSVbW80", "https://www.youtube.com/watch?v=6U4T3MJCR7k"),
    new MedipediaDTO("Brain Stem Death", "https://www.youtube.com/watch?v=i8kz_ONWHUE", "https://www.youtube.com/watch?v=OYkkaJw43Zc", "https://www.youtube.com/watch?v=XsGXUriPKto"),
    new MedipediaDTO("Brain Tumours", "https://www.youtube.com/watch?v=vedUxog7m_A", "https://www.youtube.com/watch?v=pPhI99_lsgs", "https://www.youtube.com/watch?v=YdW9i6EB2Ik"),
    new MedipediaDTO("Brain Tumours: Children", "https://www.youtube.com/watch?v=5f5592ieKBY", "https://www.youtube.com/watch?v=yDhqIdvNKas", "https://www.youtube.com/watch?v=LMg1aHgtL98"),
    new MedipediaDTO("Brain Tumours: Teenagers and young Adults", "https://www.youtube.com/watch?v=vedUxog7m_A", "https://www.youtube.com/watch?v=pPhI99_lsgs", "https://www.youtube.com/watch?v=YdW9i6EB2Ik"),
    new MedipediaDTO("Breast Cancer (Female)", "https://www.youtube.com/watch?v=sx84nHzlTaY", "https://www.youtube.com/watch?v=bcoh53N4TTk", "https://www.youtube.com/watch?v=pR3KkWQqwwk"),
    new MedipediaDTO("Breast Cancer (Male)", "https://www.youtube.com/watch?v=XsGXUriPKto", "https://www.youtube.com/watch?v=XsGXUriPKto", "https://www.youtube.com/watch?v=-JbM8CQUVj4"),
    new MedipediaDTO("Bronchiectasis", "https://www.youtube.com/watch?v=nktF_8XhpVM", "https://www.youtube.com/watch?v=Ifw5kgV0iSs&list=PLwoP7JC9o_KAaI_Ke_Tm1VKeJoNZ3DBOU", "https://www.youtube.com/watch?v=97a0rCKttlg"),
    new MedipediaDTO("Bronchitis", "https://www.youtube.com/watch?v=HO7FLvl6UPk", "https://www.youtube.com/watch?v=eNhl8Rc7shU", "https://www.youtube.com/watch?v=JIxgaHXBFYs"),
    new MedipediaDTO("Bulimia","https://www.youtube.com/watch?v=R3qISa3yms8","https://www.youtube.com/watch?v=UCovjBOzXbs", "https://www.youtube.com/watch?v=ZWUd-NoP83A"),
    new MedipediaDTO("Bunion","	https://www.youtube.com/watch?v=y0bORBXqKXQ","	https://www.youtube.com/watch?v=LGgF5JucYQ4",	"https://www.youtube.com/watch?v=RZ2NWV7rQGc"),
    new MedipediaDTO("Bursitis",	"https://www.youtube.com/watch?v=O_RoEV4enV0","https://www.youtube.com/watch?v=_3snKqUcrpA"	,"https://www.youtube.com/watch?v=_3snKqUcrpA"),
    new MedipediaDTO("Carcinoid Syndrome and Carcinoid Tumours","	https://www.youtube.com/watch?v=BqVP10fEob8","https://www.youtube.com/watch?v=XsGXUriPKto","	https://www.youtube.com/watch?v=0FNWVYDuqH4"),
    new MedipediaDTO("Deafblindness"	,"https://www.youtube.com/watch?v=DC2pVJdU_VE"	,"https://www.youtube.com/watch?v=H1g3JiRxd-8&t=230s"	,"https://www.youtube.com/watch?v=3YFOu4v-NPU"),
    new MedipediaDTO("Deep Vein Thrombosis"	,"https://www.youtube.com/watch?v=0QEo9QAqA3k"	,"https://www.youtube.com/watch?v=mpGD8BsYTi0"	,"https://www.youtube.com/watch?v=N9UEfQzdeBY"),
    new MedipediaDTO("Dehydration","https://www.youtube.com/watch?v=FuPbJwTN0xA"	,"https://www.youtube.com/watch?v=947_P2a5-PA"	,"https://www.youtube.com/watch?v=qhTeJnx9dRE"),
    new MedipediaDTO("Dementia with Lewy Bodies"	,"https://www.youtube.com/watch?v=hhE2dyeHP54"	,"https://www.youtube.com/watch?v=pPHHZA-HuBI"	,"https://www.youtube.com/watch?v=CxxwvRCE7G4"),
    new MedipediaDTO("Dental Abscess"	,"https://www.youtube.com/watch?v=YDCbiG9cZBA"	,"https://www.youtube.com/watch?v=wGa3ggPb9Yg"	,"https://www.youtube.com/watch?v=0fUJqWI35cg"),
    new MedipediaDTO("Depression"	,"https://www.youtube.com/watch?v=Yy8e4sw70ow"	,"https://www.youtube.com/watch?v=76FD9n7T9Uk"	,"https://www.youtube.com/watch?v=Yy8e4sw70ow"),
    new MedipediaDTO("Dermatitis Herpetiformis"	,"https://www.youtube.com/watch?v=j87zwSfYX1U	","https://www.youtube.com/watch?v=lpImE39nZ4Y"	,"https://www.youtube.com/watch?v=QK_iZjQB3fc"),
    new MedipediaDTO("Diabetes"	,"https://www.youtube.com/watch?v=X9ivR4y03DE"	,"https://www.youtube.com/watch?v=h2NFQcg--Rk"	,"https://www.youtube.com/watch?v=1a2Fsfa8e4I"),
    new MedipediaDTO("Diabetic Retinopathy"	,"https://www.youtube.com/watch?v=LtdWg4ygm_E"	,"https://www.youtube.com/watch?v=WRS6ARqLDEY"	,"https://www.youtube.com/watch?v=OZKusXvA-O0"),
    new MedipediaDTO("Diarrhoea"	,"https://www.youtube.com/watch?v=lEe0cfVFvvE"	,"https://www.youtube.com/watch?v=0BbhZnq6Vj4"	,"https://www.youtube.com/watch?v=1277Wwg65Ls"),
    new MedipediaDTO("Discoid Eczema"	,"https://www.youtube.com/watch?v=qCtCu0zXeRs"	,"https://www.youtube.com/watch?v=rQmRqubAgLk"	,"https://www.youtube.com/watch?v=SBufyLsO47A"),
    new MedipediaDTO("Diverticular Disease and Diverticulitis","https://www.youtube.com/watch?v=j57TBHSaL-w"	,"https://www.youtube.com/watch?v=eK8Pj6O4Mag"	,"https://www.youtube.com/watch?v=Rxv57EnnO3I"),
    new MedipediaDTO("Dizziness (Lightheadedness)"	,"https://www.youtube.com/watch?v=5nmWXo7l7Ms"	,"https://www.youtube.com/watch?v=yjT4FvbT9QE"	,"https://www.youtube.com/watch?v=p0P1GfZDraI"),
    new MedipediaDTO("Down's Syndrome","https://www.youtube.com/watch?v=c1dqG8tzuQA"	,"https://www.youtube.com/watch?v=tZBdSySCU4c"	,"https://www.youtube.com/watch?v=akC-B0Xf2bo"),
    new MedipediaDTO("Dry Mouth"	,"https://www.youtube.com/watch?v=lQJQe_n3JbQ"	,"https://www.youtube.com/watch?v=Ii38f6uoj7M	","https://www.youtube.com/watch?v=CkA78_Y-ggU"),
    new MedipediaDTO("Dysphagia (Swallowing Problems)",	"https://www.youtube.com/watch?v=VoSMA2Anq3U",	"https://www.youtube.com/watch?v=ERQarqgyfOA",	"https://www.youtube.com/watch?v=rZEVKNnMErg"),
    new MedipediaDTO("Dystonia"	,"https://www.youtube.com/watch?v=8CD767aMH4E"	,"https://www.youtube.com/watch?v=Jbf9qhSZ7gU"	,"https://www.youtube.com/watch?v=Jbf9qhSZ7gU"),
    new MedipediaDTO("Febrile Seizures"	,"https://www.youtube.com/watch?v=tYtYHX2bRew"	,"https://www.youtube.com/watch?v=O7HU09mjm1k"	,"https://www.youtube.com/watch?v=RrEeIE9edBk"),
    new MedipediaDTO("Fever in Children","https://www.youtube.com/watch?v=kJiBOFrEEhQ"	,"https://www.youtube.com/watch?v=y2W3WQW-Lec"	,"https://www.youtube.com/watch?v=Aae2FgfuB0Y"),
    new MedipediaDTO("Fibroids	","https://www.youtube.com/watch?v=AgIhy9UyoAs"	,"https://www.youtube.com/watch?v=oNxrAwKpaoI"	,"https://www.youtube.com/watch?v=JTiVWTIJkIE"),
    new MedipediaDTO("Fibromyalgia"	,"https://www.youtube.com/watch?v=sP-9r2OZgaU"	,"https://www.youtube.com/watch?v=B_H0utmVqFE"	,"https://www.youtube.com/watch?v=CqkhvKS03Qc"),
    new MedipediaDTO("Flatulence"	,"https://www.youtube.com/watch?v=eCH7_nIDuE8"	,"https://www.youtube.com/watch?v=T_5PObyntlA"	,"https://www.youtube.com/watch?v=hTOGndU30yk"),
    new MedipediaDTO("Flu","https://www.youtube.com/watch?v=PpgG_UAGqyk"	,"https://www.youtube.com/watch?v=FHFCfWelR9M"	,"https://www.youtube.com/watch?v=6EhjGrc_0w0"),
    new MedipediaDTO("Foetal Alcohol Syndrome"	,"https://www.youtube.com/watch?v=ItDMbzGBCNg"	,"https://www.youtube.com/watch?v=QRRdzhRemno"	,"https://www.youtube.com/watch?v=mniNJ0FUexY"),
    new MedipediaDTO("Folate Deficiency Anaemia"	,"https://www.youtube.com/watch?v=pJ6y6rp4WF0"	,"https://www.youtube.com/watch?v=0qoc96HfTOs","https://www.youtube.com/watch?v=hbSxO0fzD-Y"),
    new MedipediaDTO("Food Poisoning"	,"https://www.youtube.com/watch?v=4LHgSpZsT8A"	,"https://www.youtube.com/watch?v=DizdkUayQBw"	,"https://www.youtube.com/watch?v=8_VEvOYF_MA"),
    new MedipediaDTO("Fungal nail Infection"	,"https://www.youtube.com/watch?v=Rg49XFA87ic"	,"https://www.youtube.com/watch?v=Jxv9JQ6l3Tk"	,"https://www.youtube.com/watch?v=f1X5aPTzqTw"),
    new MedipediaDTO("Gallbladder Cancer"	,"https://www.youtube.com/watch?v=Zc_gAoMZ5kQ"	,"https://www.youtube.com/watch?v=5p2OSOXkHGw"	,"https://www.youtube.com/watch?v=A9BwXJf0_vo"),
    new MedipediaDTO("Gallstones"	,"https://www.youtube.com/watch?v=Bn-6rg2pwHw"	,"https://www.youtube.com/watch?v=WpQAJRyuVT4"	,"https://www.youtube.com/watch?v=tK5iWnyRJFc"),
    new MedipediaDTO("Ganglion Cyst"	,"https://www.youtube.com/watch?v=onLbYydmCIc"	,"https://www.youtube.com/watch?v=XsGXUriPKto","https://www.youtube.com/watch?v=jC2SlCoSQR0"),
    new MedipediaDTO("Gastroenteritis"	,"https://www.youtube.com/watch?v=pIDmePznLBo"	,"https://www.youtube.com/watch?v=SX12nC9_Pwg"	,"https://www.youtube.com/watch?v=HtzjuY80tTY"),
    new MedipediaDTO("Gastro-Oesophageal Reflux Disease"	,"https://www.youtube.com/watch?v=CJzRrXkVNeU	","https://www.youtube.com/watch?v=qabOTn6W3x8"	,"https://www.youtube.com/watch?v=ULxOeAs-sus"),
    new MedipediaDTO("Germ Cell Tumours",	"https://www.youtube.com/watch?v=viSjh-eUJos","https://www.youtube.com/watch?v=XsGXUriPKto","https://www.youtube.com/watch?v=8Ymvt2vBM1I"),
    new MedipediaDTO("Gout"	,"https://www.youtube.com/watch?v=SH_ceFaKLA8"	,"https://www.youtube.com/watch?v=QOa7TLnwFXs"	,"https://www.youtube.com/watch?v=xdepi9HMEpk"),
    new MedipediaDTO("Gum Disease"	,"https://www.youtube.com/watch?v=qJ3fuyTFCZw"	,"https://www.youtube.com/watch?v=94foCbFe2JQ"	,"https://www.youtube.com/watch?v=kXI4AFEeHA8"),
    new MedipediaDTO("Hairy Cell Leukaemia"	,"https://www.youtube.com/watch?v=Qy4ZHGLnt6k	","https://www.youtube.com/watch?v=XsGXUriPKto","	https://www.youtube.com/watch?v=PKepUJBEDkQ"),
    new MedipediaDTO("Hand, foot and Mouth Disease"	,"https://www.youtube.com/watch?v=RLHbq2L_qgU"	,"https://www.youtube.com/watch?v=9uixA-sHCy8"	,"https://www.youtube.com/watch?v=Mqmd8IdRg7U"),
    new MedipediaDTO("Hay Fever"	,"https://www.youtube.com/watch?v=6-wvvLtFkSU"	,"https://www.youtube.com/watch?v=T8xKcWJXDSU&t=57s"	,"https://www.youtube.com/watch?v=5WrSc4ZaRRU"),
    new MedipediaDTO("Head and Neck Cancer	","https://www.youtube.com/watch?v=ldJHKS8uhOs"	,"https://www.youtube.com/watch?v=h2riV9PpvaY"	,"https://www.youtube.com/watch?v=zRmlU5Rw-y8"),
    new MedipediaDTO("Headaches"	,"https://www.youtube.com/watch?v=rc-AhpV8S1g"	,"https://www.youtube.com/watch?v=1hX_AEBgn-k","	https://www.youtube.com/watch?v=VOLG-3FP6mE"),
    new MedipediaDTO("Hearing Loss"	,"https://www.youtube.com/watch?v=pcGz7uwnPrs"	,"https://www.youtube.com/watch?v=ubc-3WGQEsY"	,"https://www.youtube.com/watch?v=wkaTEA0LGy8"),
    new MedipediaDTO("Heart Failure"	,"https://www.youtube.com/watch?v=mhYeO2fwSps"	,"https://www.youtube.com/watch?v=k9QETgv4pto"	,"https://www.youtube.com/watch?v=PJgRZA5mE0s"),
    new MedipediaDTO("Hepatitis A"	,"https://www.youtube.com/watch?v=3LlnCTcMY5g"	,"https://www.youtube.com/watch?v=skxl71kDJ0Q"	,"https://www.youtube.com/watch?v=xmAjXggpLGM"),
    new MedipediaDTO("Hepatitis B"	,"https://www.youtube.com/watch?v=k11QcUAaNwA"	,"https://www.youtube.com/watch?v=3qJFKfurHmE"	,"https://www.youtube.com/watch?0v=PmFKIfkm9OQ"),
    new MedipediaDTO("Hepatitis C"	,"https://www.youtube.com/watch?v=wfE_s2psISw"	,"https://www.youtube.com/watch?v=VTIvrZp7K4Q"	,"https://www.youtube.com/watch?v=Jtns5TvTm3c"),
    new MedipediaDTO("Hiatus Hernia"	,"https://www.youtube.com/watch?v=y4qCQtyt844	","https://www.youtube.com/watch?v=9toAjJ9Zzqk"	,"https://www.youtube.com/watch?v=OInZ6skD2cY"),
    new MedipediaDTO("Idiopathic Pulmonary Fibrosis"	,"https://www.youtube.com/watch?v=1Kyo9Hcyiq0	","https://www.youtube.com/watch?v=aCJJz8le5Tk"	,"https://www.youtube.com/watch?v=9AL6nDNdQrg"),
    new MedipediaDTO("Impetigo"	,"https://www.youtube.com/watch?v=qV_bE5kOj6M"	,"https://www.youtube.com/watch?v=wcdLoMbKY6M	","https://www.youtube.com/watch?v=DVv47bpGBsg"),
    new MedipediaDTO("Indigestion"	,"https://www.youtube.com/watch?v=7xqxEIKkcuE"	,"https://www.youtube.com/watch?v=YDIkO2nqEFE"	,"https://www.youtube.com/watch?v=DpyF-9cScU8"),
    new MedipediaDTO("Ingrown Toenail	","https://www.youtube.com/watch?v=fkdx00H8MmM"	,"https://www.youtube.com/watch?v=u1bovuNsqOE"	,"https://www.youtube.com/watch?v=RHqvalwuU0A"),
    new MedipediaDTO("Inherited Heart Conditions	","https://www.youtube.com/watch?v=D10tac29hJA"	,"https://www.youtube.com/watch?v=aTHKu134YOc"	,"https://www.youtube.com/watch?v=aTHKu134YOc&t=31s"),
    new MedipediaDTO("Insomnia"	,"https://www.youtube.com/watch?v=_tXFhGRqggc"	,"https://www.youtube.com/watch?v=s3vaI15ICQg"	,"https://www.youtube.com/watch?v=0RRvMpScRa8"),
    new MedipediaDTO("Iron Deficiency Anaemia"	,"https://www.youtube.com/watch?v=ZhHzUEvi4eg"	,"https://www.youtube.com/watch?v=IfmJeWW4OyQ"	,"https://www.youtube.com/watch?v=-pM1jZV_a0o"),
    new MedipediaDTO("Irritable Bowel Syndrome (ibs)"	,"https://www.youtube.com/watch?v=uhoPP_IJa8c"	,"https://www.youtube.com/watch?v=QnoNNNZbxrU"	,"https://www.youtube.com/watch?v=KsJlwFemDwM"),
    new MedipediaDTO("Itching"	,"https://www.youtube.com/watch?v=0NGei3H8yRk"	,"https://www.youtube.com/watch?v=PDm1aWZpTrY"	,"https://www.youtube.com/watch?v=-H4r2UQlrXY&t=9s"),
    new MedipediaDTO("Kaposi's Sarcoma"	,"https://www.youtube.com/watch?v=BVxZuCFv8DU	","https://www.youtube.com/watch?v=MScwesdD2Aw&t=48s"	,"https://www.youtube.com/watch?v=hSuLyt8XOrQ"),
    new MedipediaDTO("Kidney Cancer",	"https://www.youtube.com/watch?v=GdhwWz6ijNU"	,"https://www.youtube.com/watch?v=JlX_AQksACA"	,"https://www.youtube.com/watch?v=xz2ojWQcx6E"),
    new MedipediaDTO("kidney Infection	","https://www.youtube.com/watch?v=9fZpSIFLLak"	,"https://www.youtube.com/watch?v=OstEkSoy0Wc"	,"https://www.youtube.com/watch?v=ec3h-w_Ywvs"),
    new MedipediaDTO("Kidney stones"	,"https://www.youtube.com/watch?v=LngbrHJkXoE"	,"https://www.youtube.com/watch?v=kd1OgaoHkNk"	,"https://www.youtube.com/watch?v=SsQCXOKtFZM"),
    new MedipediaDTO("Malaria"	,"https://www.youtube.com/watch?v=Jt5u1lX9yZI"	,"https://www.youtube.com/watch?v=qKmfnouS6KM&t=35s"	,"https://www.youtube.com/watch?v=rieVk_zl3-A"),
    new MedipediaDTO("Malignant Brain Tumour"	,"https://www.youtube.com/watch?v=FXC_RIu-N1w","https://www.youtube.com/watch?v=bat1dCxY38k"	,"https://www.youtube.com/watch?v=_PSwTt-p3JI"),
    new MedipediaDTO("Malnutrition" ,"https://www.youtube.com/watch?v=EFXofc-3KVc" ,"https://www.youtube.com/watch?v=D8MBJEaEm-I","https://www.youtube.com/watch?v=w2St8DDU5SY"),
    new MedipediaDTO("Measles","	https://www.youtube.com/watch?v=N6oQXyb69dk"	,"https://www.youtube.com/watch?v=E0_jzFXzyzg"	,"https://www.youtube.com/watch?v=6KgeqIPuigg"),
    new MedipediaDTO("Meniere's Disease",	"https://www.youtube.com/watch?v=qrk7OyAB_ss"	,"https://www.youtube.com/watch?v=lyfLPLLkNwI"	,"https://www.youtube.com/watch?v=4cm0edQI1UI"),
    new MedipediaDTO("Meningitis"	,"https://www.youtube.com/watch?v=UlQupuQjSV0"	,"https://www.youtube.com/watch?v=JmS0CD6-rsM"	,"https://www.youtube.com/watch?v=YMcqtZ57vBc"),
    new MedipediaDTO("Menopause","	https://www.youtube.com/watch?v=OGuiXHS2FWM"	,"https://www.youtube.com/watch?v=jmiayoooH_g	","https://www.youtube.com/watch?v=Fr6qPQMoifc"),
    new MedipediaDTO("Mesothelioma"	,"https://www.youtube.com/watch?v=YLW08jEGqWw"	,"https://www.youtube.com/watch?v=UpEcJHGMgLA"	,"https://www.youtube.com/watch?v=kyOMP94H5us"),
    new MedipediaDTO("Migraine","	https://www.youtube.com/watch?v=yL22X5opGhY","https://www.youtube.com/watch?v=QNnaV866K-Q"	,"https://www.youtube.com/watch?v=AQJOf-UTT6U"),
    new MedipediaDTO("Miscarriage"	,"https://www.youtube.com/watch?v=9wyPKADc8PI"	,"https://www.youtube.com/watch?v=a8wnlX5yKhE"	,"https://www.youtube.com/watch?v=3avrQJ_RJvw"),
    new MedipediaDTO("Motor Neurone Disease",	"https://www.youtube.com/watch?v=dOX0KbWRoug"	,"https://www.youtube.com/watch?v=m-zuoFtQzfw	","https://www.youtube.com/watch?v=8SisOwVWs6w"),
    new MedipediaDTO("Mouth Cancer"	,"https://www.youtube.com/watch?v=pb0wVHtP79c"	,"https://www.youtube.com/watch?v=KS1gSsB0N4c"	,"https://www.youtube.com/watch?v=ikGn6JP_oms"),
    new MedipediaDTO("Mouth Ulcer"	,"https://www.youtube.com/watch?v=_0jqei5-1so"	,"https://www.youtube.com/watch?v=UoS_JlCIBDk"	,"https://www.youtube.com/watch?v=ga8QT8nve4o"),
    new MedipediaDTO("Multiple Myeloma"	,"https://www.youtube.com/watch?v=nCFBwry1YdY"	,"https://www.youtube.com/watch?v=uvig9PP_ylc"	,"https://www.youtube.com/watch?v=dPphBP_WmY4"),
    new MedipediaDTO("Multiple Sclerosis"	,"https://www.youtube.com/watch?v=M7O78LvrNSQ"	,"https://www.youtube.com/watch?v=g5awHH1f5LU"	,"https://www.youtube.com/watch?v=jB0rAcy6mi8"),
    new MedipediaDTO("Mumps"	,"https://www.youtube.com/watch?v=ioUi727k9JM"	,"https://www.youtube.com/watch?v=Dd4qs_sXM0s"	,"https://www.youtube.com/watch?v=s3ACcn8IWFc&t=56s"),
    new MedipediaDTO("Reactive Arthritis"	,"https://www.youtube.com/watch?v=MI7NW13Q_w8"	,"https://www.youtube.com/watch?v=7ZcNjKTxzWM"	,"https://www.youtube.com/watch?v=L9XlFNV6Ghg"),
    new MedipediaDTO("Restless Legs Syndrome"	,"https://www.youtube.com/watch?v=p7G803oDx-c"	,"https://www.youtube.com/watch?v=WqbY0Owv3EQ"	,"https://www.youtube.com/watch?v=g90U6gPSWEs"),
    new MedipediaDTO("Retinoblastoma","https://www.youtube.com/watch?v=lmOrOuay_FI"	,"https://www.youtube.com/watch?v=4UL2oWPd5PU"	,"https://www.youtube.com/watch?v=NkB-BmTWW30"),
    new MedipediaDTO("Rhabdomyosarcoma"	,"https://www.youtube.com/watch?v=PLjt2DYDkDk"	,"https://www.youtube.com/watch?v=83AZKDBX-08"	,"https://www.youtube.com/watch?v=85xPmSOLvO8"),
    new MedipediaDTO("Rosacea"	,"https://www.youtube.com/watch?v=yTgSLdV_emg"	,"https://www.youtube.com/watch?v=jh9L6YzQpwo","https://www.youtube.com/watch?v=XLUQzdNsPX8"),
    new MedipediaDTO("Sepsis"	,"https://www.youtube.com/watch?v=sC8CnOsDL_o"	,"https://www.youtube.com/watch?v=_j1iE0VjfIs	","https://www.youtube.com/watch?v=s3oa5p_Y9-4"),
    new MedipediaDTO("Ulcerative Colitis"	,"https://www.youtube.com/watch?v=JMApMBY0CfQ"	,"https://www.youtube.com/watch?v=Hceq5FUpadA"	,"https://www.youtube.com/watch?v=yuK702UWeP8"),
    new MedipediaDTO("Underactive Thyroid"	,"https://www.youtube.com/watch?v=qIn8AHHB1_o"	,"https://www.youtube.com/watch?v=qYi_hJYWTKs"	,"https://www.youtube.com/watch?v=AL_JgEu7xrU"),
    new MedipediaDTO("Urinary Incontinence"	,"https://www.youtube.com/watch?v=QnpY-dOw1jM"	,"https://www.youtube.com/watch?v=V3Gunev8KA4"	,"https://www.youtube.com/watch?v=vsLBApSlPMo"),
    new MedipediaDTO("Urinary Tract Infections"	,"https://www.youtube.com/watch?v=lY2bZjggc08"	,"https://www.youtube.com/watch?v=7X7UaGQsmIo"	,"https://www.youtube.com/watch?v=F7NtF8Krs40"),
    new MedipediaDTO("Vaginal Cancer"	,"https://www.youtube.com/watch?v=cMdQ-FaUFCE"	,"https://www.youtube.com/watch?v=0NJyDeJNED4"	,"https://www.youtube.com/watch?v=t9LkRSIeV3Y"),
    new MedipediaDTO("Vaginal Thrush","	https://www.youtube.com/watch?v=TSMXFsG51Kc	","https://www.youtube.com/watch?v=fI9_YiT4NPA"	,"https://www.youtube.com/watch?v=zg2JGWWVgsQ"),
    new MedipediaDTO("Varicose Eczema"	,"https://www.youtube.com/watch?v=_zGS9tFCiXM"	,"https://www.youtube.com/watch?v=2jK8U6GK9RQ&t=25s"	,"https://www.youtube.com/watch?v=9MhS_N77BBw"),
    new MedipediaDTO("Varicose Veins"	,"https://www.youtube.com/watch?v=Ce2TjGY-r1o"	,"https://www.youtube.com/watch?v=SGrb0GAD6u4"	,"https://www.youtube.com/watch?v=AHEAGY1F0sw"),
    new MedipediaDTO("Venous Leg Ulcer"	,"https://www.youtube.com/watch?v=eH5DRVxWd6o"	,"https://www.youtube.com/watch?v=eH5DRVxWd6o"	,"https://www.youtube.com/watch?v=f0D1DePVVdo"),
    new MedipediaDTO("Venous Leg Ulcer"	,"https://www.youtube.com/watch?v=zxcCY8syWYY"	,"https://www.youtube.com/watch?v=ISmk9GO4p80	","https://www.youtube.com/watch?v=SA4xyO_TQ0I"),
    new MedipediaDTO("Vulval Cancer","https://www.youtube.com/watch?v=DKrn5FS47tk","https://www.youtube.com/watch?v=VxLTtwbbHdA"	,"https://www.youtube.com/watch?v=fcahmNsCs1s"),
    new MedipediaDTO("Warts and Verrucas"	,"https://www.youtube.com/watch?v=lHNpyr-9tNw"	,"https://www.youtube.com/watch?v=HuRRMuLYLP8"	,"https://www.youtube.com/watch?v=hJ_UAmEICok"),
    new MedipediaDTO("Whooping Cough"	,"https://www.youtube.com/watch?v=84JvqZbnwiQ"	,"https://www.youtube.com/watch?v=asbMefhyHZ4"	,"https://www.youtube.com/watch?v=4RfkxHWIBN0"),
    new MedipediaDTO("Wilms’ Tumour"	,"https://www.youtube.com/watch?v=52bqN75hpbs"	,"https://www.youtube.com/watch?v=hUJPYbjj-C0"	,"https://www.youtube.com/watch?v=Ode2LYAS5CA&t=25s"),
    new MedipediaDTO("Womb (Uterus) Cancer"	,"https://www.youtube.com/watch?v=ahATzeKl6FE "	,"https://www.youtube.com/watch?v=_ElUIwB5zoI&t=106s"	,"https://www.youtube.com/watch?v=_Qk8VMz8984&t=84s" ),
    new MedipediaDTO("Yellow Fever",	"https://www.youtube.com/watch?v=Xp99vWDgxPk&t=23s"	,"https://www.youtube.com/watch?v=9zJAqW2jw_8	","https://www.youtube.com/watch?v=84m_ItCUiHQ"),
    new MedipediaDTO("Narcolepsy"	,"https://www.youtube.com/watch?v=Ucpf_OYvs4E"	,"https://www.youtube.com/watch?v=W1CcFzdX9gE	","https://www.youtube.com/watch?v=MH8QpOrGk9E"),
    new MedipediaDTO("Obstructive Sleep Apnea"	,"https://www.youtube.com/watch?v=xEuFw_nu8oA"	,"https://www.youtube.com/watch?v=jHfCSRVtMKg","https://www.youtube.com/watch?v=8dXEgVK-fF4"),
    new MedipediaDTO("Osteoporosis"	,"https://www.youtube.com/watch?v=HkASSB9M_DY"	,"https://www.youtube.com/watch?v=Yxhz0GxHA_M"	,"https://www.youtube.com/watch?v=kosnw1IkSi8"),
    new MedipediaDTO("Otosclerosis"	,"https://www.youtube.com/watch?v=N9s26EfbKwA"	,"https://www.youtube.com/watch?v=mKdUvLKoQyI"	,"https://www.youtube.com/watch?v=idNu5ATeP6g"),
    new MedipediaDTO("Ovarian Cancer"	,"https://www.youtube.com/watch?v=ZzHaiFACHgY"	,"https://www.youtube.com/watch?v=eICQe-p4Vo4"	,"https://www.youtube.com/watch?v=n0pBz8BegPU"),
    new MedipediaDTO("Overactive Bladder Syndrome","https://www.youtube.com/watch?v=-WXDtJMNhqo"	,"https://www.youtube.com/watch?v=GtczCx7aJvU"	,"https://www.youtube.com/watch?v=fTlnk610OU0"),
    new MedipediaDTO("Carbon Monoxide Poisoning"	,"https://www.youtube.com/watch?v=wKIrbq2pWvw"	,"https://www.youtube.com/watch?v=G4T_xRMAmnM"	,"https://www.youtube.com/watch?v=csJP9JAHgnw"),
    new MedipediaDTO("Celiac Disease"	,"https://www.youtube.com/watch?v=l2KKyUo8Ujs"	,"https://www.youtube.com/watch?v=yY39vhwu0HY"	,"https://www.youtube.com/watch?v=vYhM19FllUg"),
    new MedipediaDTO("Chlamydia	","https://www.youtube.com/watch?v=DQNUZZXQH4I"	,"https://www.youtube.com/watch?v=iGgsfppw6Ds&t=287s"	,"https://www.youtube.com/watch?v=LmsVXttQ_f0"),
    new MedipediaDTO("Chronic Bronchitis"	,"https://www.youtube.com/watch?v=HO7FLvl6UPk"	,"https://www.youtube.com/watch?v=crMHWrrtx6c","https://www.youtube.com/watch?v=6Gp7qlnvMD0"),
    new MedipediaDTO("Chronic Fatigue Syndrome"	,"https://www.youtube.com/watch?v=ZLyS8bj3iJM	","https://www.youtube.com/watch?v=sYAYxXgn5qI"	,"https://www.youtube.com/watch?v=GTtEllPSWho"),
    new MedipediaDTO("Chronic Pain Syndromes"	,"https://www.youtube.com/watch?v=kMqMtO8xLM0	","https://www.youtube.com/watch?v=xVld1JsLBkw"	,"https://www.youtube.com/watch?v=FYzF4cTkhns"),
    new MedipediaDTO("Lactose Intolerance"	,"https://www.youtube.com/watch?v=iRPzSRWNjyY	","https://www.youtube.com/watch?v=TMO_67N0WAk"	,"https://www.youtube.com/watch?v=d2RiVJF5-Oo"),
    new MedipediaDTO("Long QT Syndrome"	,"https://www.youtube.com/watch?v=P3U7KNlCMKc"	,"https://www.youtube.com/watch?v=kD_QlswMIME"	,"https://www.youtube.com/watch?v=mjCT6xTZKaE"),
    new MedipediaDTO("Lung Cancer"	,"https://www.youtube.com/watch?v=Out098oAdxs"	,"https://www.youtube.com/watch?v=03oOt_4uKGI"	,"https://www.youtube.com/watch?v=9uUcBk7I9Fc"),
    new MedipediaDTO("Lupus"	,"https://www.youtube.com/watch?v=Txx2jZyJWYw"	,"https://www.youtube.com/watch?v=lLEajSvtpRM&t=22s"	,"https://www.youtube.com/watch?v=dGXPY4nThjs"),
    new MedipediaDTO("Lyme Disease"	,"https://www.youtube.com/watch?v=tX70ivbRyJ4"	,"https://www.youtube.com/watch?v=vUHIYL0u7Gk	","https://www.youtube.com/watch?v=DEu_UDqTZVM"),
    new MedipediaDTO("Stroke"	,"https://www.youtube.com/watch?v=QIAI6KOwKII"	,"https://www.youtube.com/watch?v=zuB2_OjwILI	","https://www.youtube.com/watch?v=SJYZ-AsK18k"),
    new MedipediaDTO("Sinusitis"	,"https://www.youtube.com/watch?v=RywHs4kKxjA	","https://www.youtube.com/watch?v=ysPzU5U6lqM"	,"https://www.youtube.com/watch?v=j9m-QUvhxOQ"),
    new MedipediaDTO("Salmonella",	"https://www.youtube.com/watch?v=04MS0JNw3CM"	,"https://www.youtube.com/watch?v=zXIWPnEtdkA"	,"https://www.youtube.com/watch?v=t0m9Q9x44aE"),
    new MedipediaDTO("Stomach Cancer	","https://www.youtube.com/watch?v=ncDZGEfRMRY"	,"https://www.youtube.com/watch?v=O7mV8qrn67w"	,"https://www.youtube.com/watch?v=BmltU-mMUz8"),
    new MedipediaDTO("Stillbirth","	https://www.youtube.com/watch?v=5TCWIfJrDyg"	,"https://www.youtube.com/watch?v=wW9HcOGnfMY"	,"https://www.youtube.com/watch?v=RM-NWlyDB2c"),
    new MedipediaDTO("Eye Cancer	","https://www.youtube.com/watch?v=hiVl3vGo1Lw"	,"https://www.youtube.com/watch?v=fVesFLPEUg4"	,"https://www.youtube.com/watch?v=q5z08sBchsw"),
    new MedipediaDTO("Epilepsy"	,"https://www.youtube.com/watch?v=e_Eb32Eq_fw	","https://www.youtube.com/watch?v=tznp9VFVEWA"	,"https://www.youtube.com/watch?v=L0XqL2I35n8"),
    new MedipediaDTO("High Cholesterol	","https://www.youtube.com/watch?v=wnK1Kv3XkZI"	,"https://www.youtube.com/watch?v=WVeDYDdcQ-Y	","https://www.youtube.com/watch?v=xeyyJW-xc0g"),
    new MedipediaDTO("HIV/AIDS	","https://www.youtube.com/watch?v=YxfOu_aTzH8	","https://www.youtube.com/watch?v=NXnvP_sKS9k	","https://www.youtube.com/watch?v=8OO3tTj2XfE"),
    new MedipediaDTO("Hypertension (High blood Pressure)	","https://www.youtube.com/watch?v=yINMyhbFTC4"	,"https://www.youtube.com/watch?v=7XhYHdS4La4	","https://www.youtube.com/watch?v=XbLmIoyDJuE"),
    new MedipediaDTO("Hyperthyroidism"	,"https://www.youtube.com/watch?v=NVWUqF8wQIY"	,"https://www.youtube.com/watch?v=GyAmP1XSUyA	","https://www.youtube.com/watch?v=BZs1aXliiS0"),
    new MedipediaDTO("Hypoglycemia	","https://www.youtube.com/watch?v=mCa39ONT4gI	","https://www.youtube.com/watch?v=T0rFuajPQuA	","https://www.youtube.com/watch?v=jBLMirHSKZE"),
    new MedipediaDTO("Heart Attack	","https://www.youtube.com/watch?v=3_PYnWVoUzM	","https://www.youtube.com/watch?v=3UObRoaID6U	","https://www.youtube.com/watch?v=Vts09VkK6Q8"),
    new MedipediaDTO("Heart Disease	","https://www.youtube.com/watch?v=7ftANRWBMKw"	,"https://www.youtube.com/watch?v=BLw62AhW_Kc"	,"https://www.youtube.com/watch?v=7jS5LkVTpfc"),
    new MedipediaDTO("Pancreatitis"	,"https://www.youtube.com/watch?v=-J8UflGeY48"	,"https://www.youtube.com/watch?v=3Mhen8_z7dU"	,"https://www.youtube.com/watch?v=wRWNDwlieTA"),
    new MedipediaDTO("Parkinson's Disease",	"https://www.youtube.com/watch?v=cRLB7WqX0fU"	,"https://www.youtube.com/watch?v=FroGd_CjGbk"	,"https://www.youtube.com/watch?v=in1bMrBSKdM"),
    new MedipediaDTO("Psoriasis"	,"https://www.youtube.com/watch?v=O3sauC5xGFk"	,"https://www.youtube.com/watch?v=IcE9FrZ8W58"	,"https://www.youtube.com/watch?v=ATzraLI0j5s"),
    new MedipediaDTO("Pulmonary Embolism"	,"https://www.youtube.com/watch?v=tMrCwtzcVbU"	,"https://www.youtube.com/watch?v=Kv2hqKE6URk"	,"https://www.youtube.com/watch?v=6Zy8nDtcStc"),
    new MedipediaDTO("Peripheral Neuropathy",	"https://www.youtube.com/watch?v=-mNdaKvUWZg"	,"https://www.youtube.com/watch?v=Thh29Etpo78"	,"https://www.youtube.com/watch?v=Vc_xioDS1DQ"),
    new MedipediaDTO("Lung Cancer"	,"https://www.youtube.com/watch?v=Out098oAdxs"	,"https://www.youtube.com/watch?v=03oOt_4uKGI"	,"https://www.youtube.com/watch?v=QjZq4IgXJ_s"),
  ];
}